DROP TABLE IF EXISTS test.user;
CREATE TABLE test.user (
  id INT(8) NOT NULL AUTO_INCREMENT,
  name VARCHAR(25) NOT NULL,
  age INT NOT NULL,
  isAdmin BIT NOT NULL,
  createdDate TIMESTAMP NOT NULL,
  PRIMARY KEY (id));